CUDA_VISIBLE_DEVICES=5 python3 main.py \
	--seed 42 \
	--pretrained_model meta-llama/Llama-2-13b-chat-hf \
    --length 20 \
	--max-length 20 \
	--num-iters 2000 \
	--start 0 \
	--end 50 \
	--lr-nll-portion 1.0 \
    --topk 10 \
    --output-lgt-temp 1 \
	--verbose \
    --straight-through  \
	--buffer_size 50 \
	--batch-size 4 \
	--epoch_nums 5 \
	--do_test \
	--load-checkpoint-path version_262/checkpoints/epoch=4-step=5000.ckpt \
	--test_sample_nums 20 \
	--train-data data/train.json\
	--fp16 > "logs/test.txt"